"""add oauth columns to user

Revision ID: bacc37fd60c4
Revises: d132ba47abbf
Create Date: 2026-10-01 14:01:34.649394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacc37fd60c4'
down_revision = 'd132ba47abbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
